name: Build and Deploy

on:
    push:
        branches:
            - master

jobs:
    build-and-deploy:
        runs-on: self-hosted
        steps:
            - name: Activate SSH Agent
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Checkout
              uses: actions/checkout@v2.3.1
              with:
                  persist-credentials: false

            - name: Install nodejs
              uses: actions/setup-node@v1
              with:
                  node-version: "14.x"

            - name: Translate
              run: |
                  git clone git@github.com:ygoreplay/definition-translator.git
                  cd ./definition-translator
                  yarn
                  yarn download-assets
                  yarn translate ../ ../

            - name: Commit files
              run: |
                  git config --local user.email "beyondthesophia@gmail.com"
                  git config --local user.name "Sophia"
                  git commit -m "add translation results" -a

            - name: Push changes
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: ko-KR
